# Project
group=dev.xzeroair.xat

# Minecraft & Forge
minecraft_version=1.20.1
forge_version=47.3.0
forge_version_range=[47.3.0,)
forge_loader_version_range=[47,)

# Mod options
mod_id=xat
mod_name=TrinketsAndBaubles
mod_version=0.34.1
mod_authors=XzeroAir (original), MX (1.20.1 port), keletu (Bug fixes)
mod_description=Trinkets and Baubles - a 1.20.1 port of XzeroAir's 1.12.2 mod. Adds playable races, elements, trinkets and abilities.
mod_license=GNU Affero General Public License v3.0

# Dependency coordinates
curios_version=5.9.0+1.20.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890